apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: front
        image: front
        command: ["sh"]
        args:
        - -c
        - '[ "$SERVICE_DOMAIN" == "localhost" ] && http-server dist -p 9090 || VUE_APP_URL=ws://p8080-olivia-service--$SERVICE_DOMAIN http-server dist -p 9090'
        env:
        - name: SERVICE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: staroid-envs
              key: STAROID_SERVICE_DOMAIN
---
kind: Service
apiVersion: v1
metadata:
  name: front-service
spec:
  ports:
  - name: http
    port: 9090
  selector:
    app: front
---
# see https://docs.staroid.com/references/staroid-envs.html
kind: ConfigMap
apiVersion: v1
metadata:
  name: staroid-envs
data:
  STAROID_SERVICE_DOMAIN: localhost
